"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from datetime import date
from typing import Any, Dict

import pytest

import fitbit_web_api


@pytest.fixture
async def heart_rate_time_series_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.HeartRateTimeSeriesApi, None]:
    yield fitbit_web_api.HeartRateTimeSeriesApi(api_client)


async def test_get_heart_by_date_range(
    heart_rate_time_series_api: fitbit_web_api.HeartRateTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_heart_by_date_range."""
    responses["/1/user/-/activities/heart/date/2019-01-01/2019-01-01.json"] = (
        load_test_data("heart_rate_time_series.json")
    )

    result = await heart_rate_time_series_api.get_heart_by_date_range(
        base_date="2019-01-01",
        end_date=date(2019, 1, 1),
    )

    assert result.activities_heart is not None
    assert len(result.activities_heart) == 1
    assert result.activities_heart[0].date_time == date(2019, 1, 1)
    assert result.activities_heart[0].value.resting_heart_rate == 68
    assert len(result.activities_heart[0].value.heart_rate_zones) == 4


async def test_get_heart_by_date_period(
    heart_rate_time_series_api: fitbit_web_api.HeartRateTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_heart_by_date_period."""
    responses["/1/user/-/activities/heart/date/2019-01-01/1d.json"] = load_test_data(
        "heart_rate_time_series.json"
    )

    result = await heart_rate_time_series_api.get_heart_by_date_period(
        var_date=date(2019, 1, 1),
        period="1d",
    )

    assert result.activities_heart is not None
    assert len(result.activities_heart) == 1
    assert result.activities_heart[0].date_time == date(2019, 1, 1)
    assert result.activities_heart[0].value.resting_heart_rate == 68
