"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from datetime import date
from typing import Any, Dict

import pytest

import fitbit_web_api


@pytest.fixture
async def body_time_series_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.BodyTimeSeriesApi, None]:
    yield fitbit_web_api.BodyTimeSeriesApi(api_client)


async def test_get_body_resource_by_date_range_weight(
    body_time_series_api: fitbit_web_api.BodyTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_body_resource_by_date_range with weight resource."""
    responses["/1/user/-/body/weight/date/2015-03-05/2015-03-12.json"] = load_test_data(
        "body_time_series_weight.json"
    )

    result = await body_time_series_api.get_body_resource_by_date_range(
        var_resource_path="weight",
        base_date="2015-03-05",
        end_date="2015-03-12",
    )

    assert result.body_weight is not None
    assert len(result.body_weight) == 2
    assert result.body_weight[0].date_time == date(2015, 3, 5)
    assert result.body_weight[0].value == "73.1"
    assert result.body_weight[1].date_time == date(2015, 3, 12)
    assert result.body_weight[1].value == "72.7"


async def test_get_body_resource_by_date_range_fat(
    body_time_series_api: fitbit_web_api.BodyTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_body_resource_by_date_range with fat resource."""
    responses["/1/user/-/body/fat/date/2015-03-05/2015-03-12.json"] = load_test_data(
        "body_time_series_fat.json"
    )

    result = await body_time_series_api.get_body_resource_by_date_range(
        var_resource_path="fat",
        base_date="2015-03-05",
        end_date="2015-03-12",
    )

    assert result.body_fat is not None
    assert len(result.body_fat) == 2
    assert result.body_fat[0].date_time == date(2015, 3, 5)
    assert result.body_fat[0].value == "14"
    assert result.body_fat[1].date_time == date(2015, 3, 12)
    assert result.body_fat[1].value == "13.8"


async def test_get_body_resource_by_date_period_weight(
    body_time_series_api: fitbit_web_api.BodyTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_body_resource_by_date_period with weight resource."""
    responses["/1/user/-/body/weight/date/2015-03-12/7d.json"] = load_test_data(
        "body_time_series_weight.json"
    )

    result = await body_time_series_api.get_body_resource_by_date_period(
        var_resource_path="weight",
        var_date="2015-03-12",
        period="7d",
    )

    assert result.body_weight is not None
    assert len(result.body_weight) == 2
    assert result.body_weight[0].date_time == date(2015, 3, 5)
    assert result.body_weight[0].value == "73.1"
    assert result.body_weight[1].date_time == date(2015, 3, 12)
    assert result.body_weight[1].value == "72.7"


async def test_get_body_resource_by_date_period_fat(
    body_time_series_api: fitbit_web_api.BodyTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_body_resource_by_date_period with fat resource."""
    responses["/1/user/-/body/fat/date/2015-03-12/7d.json"] = load_test_data(
        "body_time_series_fat.json"
    )

    result = await body_time_series_api.get_body_resource_by_date_period(
        var_resource_path="fat",
        var_date="2015-03-12",
        period="7d",
    )

    assert result.body_fat is not None
    assert len(result.body_fat) == 2
    assert result.body_fat[0].date_time == date(2015, 3, 5)
    assert result.body_fat[0].value == "14"
    assert result.body_fat[1].date_time == date(2015, 3, 12)
    assert result.body_fat[1].value == "13.8"
