"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from typing import Any, Dict, List

import pytest

import fitbit_web_api

DEVICES_PATH = "/1/user/-/devices.json"


@pytest.fixture
async def devices_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.DevicesApi, None]:
    yield fitbit_web_api.DevicesApi(api_client)


async def test_get_devices(
    devices_api: fitbit_web_api.DevicesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_devices."""
    devices_data: List[Dict[str, Any]] = load_test_data("devices.json")
    responses[DEVICES_PATH] = devices_data

    devices = await devices_api.get_devices()
    assert len(devices) == 2
    device = devices[0]
    assert device.battery == "Medium"
    assert device.battery_level == 60
    assert device.device_version == "Charge 2"
    assert device.id == "816713257"
    assert device.mac == "16ADD56D54GD"
    assert device.type == "TRACKER"
