"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.models.get_food_log_response import GetFoodLogResponse


class TestGetFoodLogResponse(unittest.TestCase):
    """GetFoodLogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFoodLogResponse:
        """
        Test GetFoodLogResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `GetFoodLogResponse`
        """
        model = GetFoodLogResponse()
        if include_optional:
            return GetFoodLogResponse(
                foods = [
                    fitbit_web_api.models.food_log_entry.FoodLogEntry(
                        is_favorite = True,
                        log_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        log_id = 56,
                        logged_food = fitbit_web_api.models.logged_food.LoggedFood(
                            access_level = 'PUBLIC',
                            amount = 1.337,
                            brand = '',
                            calories = 56,
                            food_id = 56,
                            locale = '',
                            meal_type_id = 56,
                            name = '',
                            unit = fitbit_web_api.models.logged_food_unit.LoggedFood_unit(
                                id = 56,
                                name = '',
                                plural = '', ),
                            units = [
                                56
                                ], ),
                        nutritional_values = fitbit_web_api.models.nutritional_values.NutritionalValues(
                            calories = 56,
                            carbs = 1.337,
                            fat = 1.337,
                            fiber = 1.337,
                            protein = 1.337,
                            sodium = 1.337, ), )
                    ],
                goals = fitbit_web_api.models.food_goals.FoodGoals(
                    calories = 56, ),
                summary = fitbit_web_api.models.nutritional_values.NutritionalValues(
                    calories = 56,
                    carbs = 1.337,
                    fat = 1.337,
                    fiber = 1.337,
                    protein = 1.337,
                    sodium = 1.337, )
            )
        else:
            return GetFoodLogResponse(
        )
        """

    def testGetFoodLogResponse(self):
        """Test GetFoodLogResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
