"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator
from typing import Any, Dict

import pytest

import fitbit_web_api

PROFILE_PATH = "/1/user/-/profile.json"
PROFILE_DATA = {
    "user": {
        "encodedId": "some-profile-id",
        "locale": "en_US",
        "fullName": "Full name",
        "displayName": "Display name",
        "displayNameSetting": "name",
        "firstName": "First",
        "lastName": "Last",
    }
}


@pytest.fixture
async def user_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.UserApi, None]:
    yield fitbit_web_api.UserApi(api_client)


async def test_get_profile_async(
    user_api: fitbit_web_api.UserApi, responses: Dict[str, Any]
) -> None:
    """Test case for get_profile as an async request."""
    responses[PROFILE_PATH] = PROFILE_DATA

    profile = await user_api.get_profile()
    assert profile.user is not None
    assert profile.user.encoded_id == "some-profile-id"
    assert profile.user.full_name == "Full name"
    assert profile.user.display_name == "Display name"
    assert profile.user.first_name == "First"
    assert profile.user.last_name == "Last"
