"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from datetime import date
from typing import Any, Dict

import pytest

import fitbit_web_api


@pytest.fixture
async def activity_time_series_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.ActivityTimeSeriesApi, None]:
    yield fitbit_web_api.ActivityTimeSeriesApi(api_client)


async def test_get_activities_resource_by_date_range_steps(
    activity_time_series_api: fitbit_web_api.ActivityTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_activities_resource_by_date_range with steps resource."""
    responses["/1/user/-/activities/steps/date/2018-12-26/2019-01-01.json"] = (
        load_test_data("activity_time_series_steps.json")
    )

    result = await activity_time_series_api.get_activities_resource_by_date_range(
        var_resource_path="steps",
        base_date=date(2018, 12, 26),
        end_date=date(2019, 1, 1),
    )

    assert result.activities_steps is not None
    assert len(result.activities_steps) == 7
    assert result.activities_steps[0].date_time == date(2018, 12, 26)
    assert result.activities_steps[0].value == "2504"
    assert result.activities_steps[6].date_time == date(2019, 1, 1)
    assert result.activities_steps[6].value == "1698"


async def test_get_activities_resource_by_date_range_calories(
    activity_time_series_api: fitbit_web_api.ActivityTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_activities_resource_by_date_range with calories resource."""
    responses["/1/user/-/activities/calories/date/2018-12-26/2019-01-01.json"] = (
        load_test_data("activity_time_series_calories.json")
    )

    result = await activity_time_series_api.get_activities_resource_by_date_range(
        var_resource_path="calories",
        base_date=date(2018, 12, 26),
        end_date=date(2019, 1, 1),
    )

    assert result.activities_calories is not None
    assert len(result.activities_calories) == 7
    assert result.activities_calories[0].date_time == date(2018, 12, 26)
    assert result.activities_calories[0].value == "2143"
    assert result.activities_calories[6].date_time == date(2019, 1, 1)
    assert result.activities_calories[6].value == "2098"


async def test_get_activities_resource_by_date_period_steps(
    activity_time_series_api: fitbit_web_api.ActivityTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_activities_resource_by_date_period with steps resource."""
    responses["/1/user/-/activities/steps/date/2019-01-01/7d.json"] = load_test_data(
        "activity_time_series_steps.json"
    )

    result = await activity_time_series_api.get_activities_resource_by_date_period(
        var_resource_path="steps",
        var_date=date(2019, 1, 1),
        period="7d",
    )

    assert result.activities_steps is not None
    assert len(result.activities_steps) == 7
    assert result.activities_steps[0].date_time == date(2018, 12, 26)
    assert result.activities_steps[0].value == "2504"
    assert result.activities_steps[6].date_time == date(2019, 1, 1)
    assert result.activities_steps[6].value == "1698"


async def test_get_activities_resource_by_date_period_calories(
    activity_time_series_api: fitbit_web_api.ActivityTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_activities_resource_by_date_period with calories resource."""
    responses["/1/user/-/activities/calories/date/2019-01-01/7d.json"] = load_test_data(
        "activity_time_series_calories.json"
    )

    result = await activity_time_series_api.get_activities_resource_by_date_period(
        var_resource_path="calories",
        var_date=date(2019, 1, 1),
        period="7d",
    )

    assert result.activities_calories is not None
    assert len(result.activities_calories) == 7
    assert result.activities_calories[0].date_time == date(2018, 12, 26)
    assert result.activities_calories[0].value == "2143"
    assert result.activities_calories[6].date_time == date(2019, 1, 1)
    assert result.activities_calories[6].value == "2098"
