"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.models.get_sp_o2_summary_response import GetSpO2SummaryResponse


class TestGetSpO2SummaryResponse(unittest.TestCase):
    """GetSpO2SummaryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpO2SummaryResponse:
        """
        Test GetSpO2SummaryResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `GetSpO2SummaryResponse`
        """
        model = GetSpO2SummaryResponse()
        if include_optional:
            return GetSpO2SummaryResponse(
                spo2 = [
                    fitbit_web_api.models.sp_o2_summary.SpO2Summary(
                        date_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        value = fitbit_web_api.models.sp_o2_summary_value.SpO2Summary_value(
                            avg = 1.337,
                            min = 1.337,
                            max = 1.337, ), )
                    ]
            )
        else:
            return GetSpO2SummaryResponse(
        )
        """

    def testGetSpO2SummaryResponse(self):
        """Test GetSpO2SummaryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
