"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.models.get_sp_o2_intraday_response import GetSpO2IntradayResponse


class TestGetSpO2IntradayResponse(unittest.TestCase):
    """GetSpO2IntradayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSpO2IntradayResponse:
        """
        Test GetSpO2IntradayResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `GetSpO2IntradayResponse`
        """
        model = GetSpO2IntradayResponse()
        if include_optional:
            return GetSpO2IntradayResponse(
                spo2 = [
                    fitbit_web_api.models.get_sp_o2_intraday_response_spo2_inner.GetSpO2IntradayResponse_spo2_inner(
                        date_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        minutes = [
                            fitbit_web_api.models.sp_o2_intraday_minute.SpO2IntradayMinute(
                                minute = '',
                                value = 1.337, )
                            ], )
                    ]
            )
        else:
            return GetSpO2IntradayResponse(
        )
        """

    def testGetSpO2IntradayResponse(self):
        """Test GetSpO2IntradayResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
