"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.models.get_activity_log_list_response import (
    GetActivityLogListResponse,
)


class TestGetActivityLogListResponse(unittest.TestCase):
    """GetActivityLogListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetActivityLogListResponse:
        """
        Test GetActivityLogListResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `GetActivityLogListResponse`
        """
        model = GetActivityLogListResponse()
        if include_optional:
            return GetActivityLogListResponse(
                activities = [
                    fitbit_web_api.models.activity_log.ActivityLog(
                        activity_id = 56,
                        activity_parent_id = 56,
                        activity_parent_name = '',
                        calories = 56,
                        description = '',
                        distance = 1.337,
                        duration = 56,
                        has_active_zone_minutes = True,
                        has_start_time = True,
                        is_favorite = True,
                        last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        log_id = 56,
                        name = '',
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        start_time = '',
                        steps = 56, )
                    ],
                pagination = fitbit_web_api.models.get_activity_log_list_response_pagination.GetActivityLogListResponse_pagination(
                    after_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                    limit = 56,
                    next = '',
                    offset = 56,
                    previous = '',
                    sort = 'asc', )
            )
        else:
            return GetActivityLogListResponse(
        )
        """

    def testGetActivityLogListResponse(self):
        """Test GetActivityLogListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
