"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from datetime import date
from typing import Any, Dict

import pytest

import fitbit_web_api


@pytest.fixture
async def nutrition_time_series_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.NutritionTimeSeriesApi, None]:
    yield fitbit_web_api.NutritionTimeSeriesApi(api_client)


async def test_get_foods_by_date_range_water(
    nutrition_time_series_api: fitbit_web_api.NutritionTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_foods_by_date_range with water resource."""
    responses["/1/user/-/foods/log/water/date/2019-03-15/2019-03-21.json"] = (
        load_test_data("nutrition_time_series_water.json")
    )

    result = await nutrition_time_series_api.get_foods_by_date_range(
        var_resource_path="water",
        base_date=date(2019, 3, 15),
        end_date=date(2019, 3, 21),
    )

    assert result.foods_log_water is not None
    assert len(result.foods_log_water) == 7
    assert result.foods_log_water[0].date_time == date(2019, 3, 15)
    assert result.foods_log_water[0].value == "0.0"
    assert result.foods_log_water[6].date_time == date(2019, 3, 21)
    assert result.foods_log_water[6].value == "1892.7099609375"


async def test_get_foods_by_date_range_calories(
    nutrition_time_series_api: fitbit_web_api.NutritionTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_foods_by_date_range with caloriesIn resource."""
    responses["/1/user/-/foods/log/caloriesIn/date/2019-03-15/2019-03-21.json"] = (
        load_test_data("nutrition_time_series_calories.json")
    )

    result = await nutrition_time_series_api.get_foods_by_date_range(
        var_resource_path="caloriesIn",
        base_date=date(2019, 3, 15),
        end_date=date(2019, 3, 21),
    )

    assert result.foods_log_calories_in is not None
    assert len(result.foods_log_calories_in) == 7
    assert result.foods_log_calories_in[0].date_time == date(2019, 3, 15)
    assert result.foods_log_calories_in[0].value == "2100"
    assert result.foods_log_calories_in[6].date_time == date(2019, 3, 21)
    assert result.foods_log_calories_in[6].value == "2150"


async def test_get_foods_resource_by_date_period_water(
    nutrition_time_series_api: fitbit_web_api.NutritionTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_foods_resource_by_date_period with water resource."""
    responses["/1/user/-/foods/log/water/date/2019-03-21/7d.json"] = load_test_data(
        "nutrition_time_series_water.json"
    )

    result = await nutrition_time_series_api.get_foods_resource_by_date_period(
        var_resource_path="water",
        var_date=date(2019, 3, 21),
        period="7d",
    )

    assert result.foods_log_water is not None
    assert len(result.foods_log_water) == 7
    assert result.foods_log_water[0].date_time == date(2019, 3, 15)
    assert result.foods_log_water[0].value == "0.0"
    assert result.foods_log_water[6].date_time == date(2019, 3, 21)
    assert result.foods_log_water[6].value == "1892.7099609375"


async def test_get_foods_resource_by_date_period_calories(
    nutrition_time_series_api: fitbit_web_api.NutritionTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_foods_resource_by_date_period with caloriesIn resource."""
    responses["/1/user/-/foods/log/caloriesIn/date/2019-03-21/7d.json"] = (
        load_test_data("nutrition_time_series_calories.json")
    )

    result = await nutrition_time_series_api.get_foods_resource_by_date_period(
        var_resource_path="caloriesIn",
        var_date=date(2019, 3, 21),
        period="7d",
    )

    assert result.foods_log_calories_in is not None
    assert len(result.foods_log_calories_in) == 7
    assert result.foods_log_calories_in[0].date_time == date(2019, 3, 15)
    assert result.foods_log_calories_in[0].value == "2100"
    assert result.foods_log_calories_in[6].date_time == date(2019, 3, 21)
    assert result.foods_log_calories_in[6].value == "2150"
