"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from collections.abc import AsyncGenerator, Callable
from datetime import date
from typing import Any, Dict

import pytest

import fitbit_web_api


@pytest.fixture
async def heart_rate_intraday_api(
    api_client: fitbit_web_api.ApiClient,
) -> AsyncGenerator[fitbit_web_api.HeartRateIntradayTimeSeriesApi, None]:
    yield fitbit_web_api.HeartRateIntradayTimeSeriesApi(api_client)


async def test_get_heart_by_date_intraday(
    heart_rate_intraday_api: fitbit_web_api.HeartRateIntradayTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_heart_by_date_intraday."""
    responses["/1/user/-/activities/heart/date/2019-01-01/1d/1sec.json"] = (
        load_test_data("heart_rate_intraday.json")
    )

    result = await heart_rate_intraday_api.get_heart_by_date_intraday(
        var_date="2019-01-01",
        detail_level="1sec",
    )

    assert result.activities_heart is not None
    assert len(result.activities_heart) == 1
    assert result.activities_heart[0].date_time == date(2019, 1, 1)
    assert result.activities_heart_intraday is not None
    assert result.activities_heart_intraday.dataset_interval == 1
    assert result.activities_heart_intraday.dataset_type == "second"
    assert len(result.activities_heart_intraday.dataset) == 2


async def test_get_heart_by_date_range_intraday(
    heart_rate_intraday_api: fitbit_web_api.HeartRateIntradayTimeSeriesApi,
    responses: Dict[str, Any],
    load_test_data: Callable[[str], Any],
) -> None:
    """Test case for get_heart_by_date_range_intraday."""
    responses["/1/user/-/activities/heart/date/2019-01-01/2019-01-01/1sec.json"] = (
        load_test_data("heart_rate_intraday.json")
    )

    result = await heart_rate_intraday_api.get_heart_by_date_range_intraday(
        var_date="2019-01-01",
        end_date="2019-01-01",
        detail_level="1sec",
    )

    assert result.activities_heart is not None
    assert result.activities_heart_intraday is not None
    assert len(result.activities_heart_intraday.dataset) == 2
    assert result.activities_heart_intraday.dataset[0].time == "00:00:00"
    assert result.activities_heart_intraday.dataset[0].value == 67
