# coding: utf-8

# flake8: noqa
"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from fitbit_web_api.models.activity_goals import ActivityGoals
from fitbit_web_api.models.activity_log import ActivityLog
from fitbit_web_api.models.activity_summary import ActivitySummary
from fitbit_web_api.models.activity_summary_distances_inner import (
    ActivitySummaryDistancesInner,
)
from fitbit_web_api.models.activity_time_series_datapoint import (
    ActivityTimeSeriesDatapoint,
)
from fitbit_web_api.models.alarm import Alarm
from fitbit_web_api.models.alarm_response import AlarmResponse
from fitbit_web_api.models.badge import Badge
from fitbit_web_api.models.create_sleep_goal_response import CreateSleepGoalResponse
from fitbit_web_api.models.create_sleep_log_response import CreateSleepLogResponse
from fitbit_web_api.models.device import Device
from fitbit_web_api.models.food_item import FoodItem
from fitbit_web_api.models.get_activity_goals_response import GetActivityGoalsResponse
from fitbit_web_api.models.get_activity_log_list_response import (
    GetActivityLogListResponse,
)
from fitbit_web_api.models.get_activity_log_list_response_pagination import (
    GetActivityLogListResponsePagination,
)
from fitbit_web_api.models.get_activity_time_series_response import (
    GetActivityTimeSeriesResponse,
)
from fitbit_web_api.models.get_alarms_response import GetAlarmsResponse
from fitbit_web_api.models.get_badges_response import GetBadgesResponse
from fitbit_web_api.models.get_daily_activity_summary_response import (
    GetDailyActivitySummaryResponse,
)
from fitbit_web_api.models.get_profile_response import GetProfileResponse
from fitbit_web_api.models.get_sleep_goal_response import GetSleepGoalResponse
from fitbit_web_api.models.get_sleep_log_by_date_range_response import (
    GetSleepLogByDateRangeResponse,
)
from fitbit_web_api.models.get_sleep_log_by_date_response import (
    GetSleepLogByDateResponse,
)
from fitbit_web_api.models.get_sleep_log_list_response import GetSleepLogListResponse
from fitbit_web_api.models.get_sleep_log_list_response_pagination import (
    GetSleepLogListResponsePagination,
)
from fitbit_web_api.models.lifetime_stats import LifetimeStats
from fitbit_web_api.models.lifetime_stats_best import LifetimeStatsBest
from fitbit_web_api.models.lifetime_stats_best_total import LifetimeStatsBestTotal
from fitbit_web_api.models.lifetime_stats_best_total_distance import (
    LifetimeStatsBestTotalDistance,
)
from fitbit_web_api.models.lifetime_stats_best_total_floors import (
    LifetimeStatsBestTotalFloors,
)
from fitbit_web_api.models.lifetime_stats_best_total_steps import (
    LifetimeStatsBestTotalSteps,
)
from fitbit_web_api.models.lifetime_stats_best_tracker import LifetimeStatsBestTracker
from fitbit_web_api.models.lifetime_stats_lifetime import LifetimeStatsLifetime
from fitbit_web_api.models.lifetime_stats_lifetime_total import (
    LifetimeStatsLifetimeTotal,
)
from fitbit_web_api.models.lifetime_stats_lifetime_tracker import (
    LifetimeStatsLifetimeTracker,
)
from fitbit_web_api.models.meal import Meal
from fitbit_web_api.models.sleep_goal import SleepGoal
from fitbit_web_api.models.sleep_log import SleepLog
from fitbit_web_api.models.sleep_log_levels import SleepLogLevels
from fitbit_web_api.models.sleep_log_levels_data_inner import SleepLogLevelsDataInner
from fitbit_web_api.models.sleep_log_levels_summary_value import (
    SleepLogLevelsSummaryValue,
)
from fitbit_web_api.models.sleep_meta import SleepMeta
from fitbit_web_api.models.sleep_summary import SleepSummary
from fitbit_web_api.models.user import User
from fitbit_web_api.models.user_features import UserFeatures
