"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date, datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing_extensions import Self


class ActivityLog(BaseModel):
    """
    ActivityLog
    """

    activity_id: Optional[StrictInt] = Field(
        default=None, description="The ID of the activity.", alias="activityId"
    )
    activity_parent_id: Optional[StrictInt] = Field(
        default=None,
        description="The ID of the top level ('parent') activity.",
        alias="activityParentId",
    )
    activity_parent_name: Optional[StrictStr] = Field(
        default=None,
        description="The name of the top level ('parent') activity.",
        alias="activityParentName",
    )
    calories: Optional[StrictInt] = Field(
        default=None, description="Number of calories burned during the exercise."
    )
    description: Optional[StrictStr] = Field(
        default=None, description="The description of the recorded exercise."
    )
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Distance traveled during the on-device recorded exercise.",
    )
    duration: Optional[StrictInt] = Field(
        default=None,
        description="The activeDuration (milliseconds) + any pauses that occurred during the activity recording.",
    )
    has_active_zone_minutes: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if the activity has active zone minutes.",
        alias="hasActiveZoneMinutes",
    )
    has_start_time: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if the activity has a start time.",
        alias="hasStartTime",
    )
    is_favorite: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if the activity is a favorite.",
        alias="isFavorite",
    )
    last_modified: Optional[datetime] = Field(
        default=None,
        description="Timestamp the exercise was last modified.",
        alias="lastModified",
    )
    log_id: Optional[StrictInt] = Field(
        default=None,
        description="The activity log identifier for the exercise.",
        alias="logId",
    )
    name: Optional[StrictStr] = Field(
        default=None, description="Name of the recorded exercise."
    )
    start_date: Optional[date] = Field(
        default=None,
        description="The start date of the recorded exercise.",
        alias="startDate",
    )
    start_time: Optional[StrictStr] = Field(
        default=None,
        description="The start time of the recorded exercise.",
        alias="startTime",
    )
    steps: Optional[StrictInt] = Field(
        default=None, description="Number of steps recorded during the exercise."
    )
    __properties: ClassVar[List[str]] = [
        "activityId",
        "activityParentId",
        "activityParentName",
        "calories",
        "description",
        "distance",
        "duration",
        "hasActiveZoneMinutes",
        "hasStartTime",
        "isFavorite",
        "lastModified",
        "logId",
        "name",
        "startDate",
        "startTime",
        "steps",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActivityLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActivityLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "activityId": obj.get("activityId"),
                "activityParentId": obj.get("activityParentId"),
                "activityParentName": obj.get("activityParentName"),
                "calories": obj.get("calories"),
                "description": obj.get("description"),
                "distance": obj.get("distance"),
                "duration": obj.get("duration"),
                "hasActiveZoneMinutes": obj.get("hasActiveZoneMinutes"),
                "hasStartTime": obj.get("hasStartTime"),
                "isFavorite": obj.get("isFavorite"),
                "lastModified": obj.get("lastModified"),
                "logId": obj.get("logId"),
                "name": obj.get("name"),
                "startDate": obj.get("startDate"),
                "startTime": obj.get("startTime"),
                "steps": obj.get("steps"),
            }
        )
        return _obj
