"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class Alarm(BaseModel):
    """
    Alarm
    """

    alarm_id: Optional[StrictInt] = Field(
        default=None,
        description="Numerical value representing the alarm ID.",
        alias="alarmId",
    )
    deleted: Optional[StrictBool] = Field(
        default=None, description="Indicates if an alarm has been deleted."
    )
    enabled: Optional[StrictBool] = Field(
        default=None, description="Indicates if an alarm is enabled."
    )
    recurring: Optional[StrictBool] = Field(
        default=None, description="Indicates if an alarm is recurring."
    )
    snooze_count: Optional[StrictInt] = Field(
        default=None,
        description="Indicates the number of times the alarm will snooze.",
        alias="snoozeCount",
    )
    snooze_length: Optional[StrictInt] = Field(
        default=None,
        description="Indicates the time in minutes between snooze periods.",
        alias="snoozeLength",
    )
    synced_to_device: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if the alarm is synced to the device.",
        alias="syncedToDevice",
    )
    time: Optional[StrictStr] = Field(
        default=None, description="The time and UTC offset for the specified alarm."
    )
    vibe: Optional[StrictStr] = Field(
        default=None, description="Returns the type of vibration configured."
    )
    week_days: Optional[List[StrictStr]] = Field(
        default=None,
        description="Returns the recurring days of the week which the alarm is set.",
        alias="weekDays",
    )
    label: Optional[StrictStr] = Field(
        default=None, description="Label or name for the alarm."
    )
    __properties: ClassVar[List[str]] = [
        "alarmId",
        "deleted",
        "enabled",
        "recurring",
        "snoozeCount",
        "snoozeLength",
        "syncedToDevice",
        "time",
        "vibe",
        "weekDays",
        "label",
    ]

    @field_validator("vibe")
    def vibe_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["DEFAULT"]):
            raise ValueError("must be one of enum values ('DEFAULT')")
        return value

    @field_validator("week_days")
    def week_days_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(
                [
                    "MONDAY",
                    "TUESDAY",
                    "WEDNESDAY",
                    "THURSDAY",
                    "FRIDAY",
                    "SATURDAY",
                    "SUNDAY",
                ]
            ):
                raise ValueError(
                    "each list item must be one of ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')"
                )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Alarm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Alarm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "alarmId": obj.get("alarmId"),
                "deleted": obj.get("deleted"),
                "enabled": obj.get("enabled"),
                "recurring": obj.get("recurring"),
                "snoozeCount": obj.get("snoozeCount"),
                "snoozeLength": obj.get("snoozeLength"),
                "syncedToDevice": obj.get("syncedToDevice"),
                "time": obj.get("time"),
                "vibe": obj.get("vibe"),
                "weekDays": obj.get("weekDays"),
                "label": obj.get("label"),
            }
        )
        return _obj
