"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing_extensions import Self


class AzmValue(BaseModel):
    """
    AzmValue
    """

    active_zone_minutes: Optional[StrictInt] = Field(
        default=None,
        description="Total count of active zone minutes earned.",
        alias="activeZoneMinutes",
    )
    fat_burn_active_zone_minutes: Optional[StrictInt] = Field(
        default=None,
        description="The number of active zone minutes in the fat burn heart rate zone.",
        alias="fatBurnActiveZoneMinutes",
    )
    cardio_active_zone_minutes: Optional[StrictInt] = Field(
        default=None,
        description="The number of active zone minutes in the cardio heart rate zone.",
        alias="cardioActiveZoneMinutes",
    )
    peak_active_zone_minutes: Optional[StrictInt] = Field(
        default=None,
        description="The number of active zone minutes in the peak heart rate zone.",
        alias="peakActiveZoneMinutes",
    )
    __properties: ClassVar[List[str]] = [
        "activeZoneMinutes",
        "fatBurnActiveZoneMinutes",
        "cardioActiveZoneMinutes",
        "peakActiveZoneMinutes",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AzmValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AzmValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "activeZoneMinutes": obj.get("activeZoneMinutes"),
                "fatBurnActiveZoneMinutes": obj.get("fatBurnActiveZoneMinutes"),
                "cardioActiveZoneMinutes": obj.get("cardioActiveZoneMinutes"),
                "peakActiveZoneMinutes": obj.get("peakActiveZoneMinutes"),
            }
        )
        return _obj
