"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from fitbit_web_api.models.breathing_rate_intraday_summary import (
    BreathingRateIntradaySummary,
)


class BreathingRateIntradayValue(BaseModel):
    """
    BreathingRateIntradayValue
    """

    light_sleep_summary: Optional[BreathingRateIntradaySummary] = Field(
        default=None, alias="lightSleepSummary"
    )
    deep_sleep_summary: Optional[BreathingRateIntradaySummary] = Field(
        default=None, alias="deepSleepSummary"
    )
    rem_sleep_summary: Optional[BreathingRateIntradaySummary] = Field(
        default=None, alias="remSleepSummary"
    )
    full_sleep_summary: Optional[BreathingRateIntradaySummary] = Field(
        default=None, alias="fullSleepSummary"
    )
    __properties: ClassVar[List[str]] = [
        "lightSleepSummary",
        "deepSleepSummary",
        "remSleepSummary",
        "fullSleepSummary",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BreathingRateIntradayValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of light_sleep_summary
        if self.light_sleep_summary:
            _dict["lightSleepSummary"] = self.light_sleep_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deep_sleep_summary
        if self.deep_sleep_summary:
            _dict["deepSleepSummary"] = self.deep_sleep_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rem_sleep_summary
        if self.rem_sleep_summary:
            _dict["remSleepSummary"] = self.rem_sleep_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of full_sleep_summary
        if self.full_sleep_summary:
            _dict["fullSleepSummary"] = self.full_sleep_summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BreathingRateIntradayValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "lightSleepSummary": BreathingRateIntradaySummary.from_dict(
                    obj["lightSleepSummary"]
                )
                if obj.get("lightSleepSummary") is not None
                else None,
                "deepSleepSummary": BreathingRateIntradaySummary.from_dict(
                    obj["deepSleepSummary"]
                )
                if obj.get("deepSleepSummary") is not None
                else None,
                "remSleepSummary": BreathingRateIntradaySummary.from_dict(
                    obj["remSleepSummary"]
                )
                if obj.get("remSleepSummary") is not None
                else None,
                "fullSleepSummary": BreathingRateIntradaySummary.from_dict(
                    obj["fullSleepSummary"]
                )
                if obj.get("fullSleepSummary") is not None
                else None,
            }
        )
        return _obj
