"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from fitbit_web_api.models.azm_intraday_dataset import AzmIntradayDataset
from fitbit_web_api.models.get_azm_intraday_response_activities_active_zone_minutes_inner import (
    GetAzmIntradayResponseActivitiesActiveZoneMinutesInner,
)


class GetAzmIntradayResponse(BaseModel):
    """
    GetAzmIntradayResponse
    """

    activities_active_zone_minutes: Optional[
        List[GetAzmIntradayResponseActivitiesActiveZoneMinutesInner]
    ] = Field(default=None, alias="activities-active-zone-minutes")
    activities_active_zone_minutes_intraday: Optional[AzmIntradayDataset] = Field(
        default=None, alias="activities-active-zone-minutes-intraday"
    )
    __properties: ClassVar[List[str]] = [
        "activities-active-zone-minutes",
        "activities-active-zone-minutes-intraday",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAzmIntradayResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in activities_active_zone_minutes (list)
        _items = []
        if self.activities_active_zone_minutes:
            for (
                _item_activities_active_zone_minutes
            ) in self.activities_active_zone_minutes:
                if _item_activities_active_zone_minutes:
                    _items.append(_item_activities_active_zone_minutes.to_dict())
            _dict["activities-active-zone-minutes"] = _items
        # override the default output from pydantic by calling `to_dict()` of activities_active_zone_minutes_intraday
        if self.activities_active_zone_minutes_intraday:
            _dict["activities-active-zone-minutes-intraday"] = (
                self.activities_active_zone_minutes_intraday.to_dict()
            )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAzmIntradayResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "activities-active-zone-minutes": [
                    GetAzmIntradayResponseActivitiesActiveZoneMinutesInner.from_dict(
                        _item
                    )
                    for _item in obj["activities-active-zone-minutes"]
                ]
                if obj.get("activities-active-zone-minutes") is not None
                else None,
                "activities-active-zone-minutes-intraday": AzmIntradayDataset.from_dict(
                    obj["activities-active-zone-minutes-intraday"]
                )
                if obj.get("activities-active-zone-minutes-intraday") is not None
                else None,
            }
        )
        return _obj
