"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from fitbit_web_api.models.activity_time_series_datapoint import (
    ActivityTimeSeriesDatapoint,
)


class GetActivityTimeSeriesResponse(BaseModel):
    """
    GetActivityTimeSeriesResponse
    """

    activities_activity_calories: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-activityCalories"
    )
    activities_calories: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-calories"
    )
    activities_calories_bmr: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-caloriesBMR"
    )
    activities_distance: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-distance"
    )
    activities_elevation: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-elevation"
    )
    activities_floors: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-floors"
    )
    activities_minutes_sedentary: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-minutesSedentary"
    )
    activities_minutes_lightly_active: Optional[List[ActivityTimeSeriesDatapoint]] = (
        Field(default=None, alias="activities-minutesLightlyActive")
    )
    activities_minutes_fairly_active: Optional[List[ActivityTimeSeriesDatapoint]] = (
        Field(default=None, alias="activities-minutesFairlyActive")
    )
    activities_minutes_very_active: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-minutesVeryActive"
    )
    activities_steps: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-steps"
    )
    activities_swimming_strokes: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-swimming-strokes"
    )
    activities_tracker_activity_calories: Optional[
        List[ActivityTimeSeriesDatapoint]
    ] = Field(default=None, alias="activities-tracker-activityCalories")
    activities_tracker_calories: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-tracker-calories"
    )
    activities_tracker_distance: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-tracker-distance"
    )
    activities_tracker_elevation: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-tracker-elevation"
    )
    activities_tracker_floors: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-tracker-floors"
    )
    activities_tracker_minutes_sedentary: Optional[
        List[ActivityTimeSeriesDatapoint]
    ] = Field(default=None, alias="activities-tracker-minutesSedentary")
    activities_tracker_minutes_lightly_active: Optional[
        List[ActivityTimeSeriesDatapoint]
    ] = Field(default=None, alias="activities-tracker-minutesLightlyActive")
    activities_tracker_minutes_fairly_active: Optional[
        List[ActivityTimeSeriesDatapoint]
    ] = Field(default=None, alias="activities-tracker-minutesFairlyActive")
    activities_tracker_minutes_very_active: Optional[
        List[ActivityTimeSeriesDatapoint]
    ] = Field(default=None, alias="activities-tracker-minutesVeryActive")
    activities_tracker_steps: Optional[List[ActivityTimeSeriesDatapoint]] = Field(
        default=None, alias="activities-tracker-steps"
    )
    __properties: ClassVar[List[str]] = [
        "activities-activityCalories",
        "activities-calories",
        "activities-caloriesBMR",
        "activities-distance",
        "activities-elevation",
        "activities-floors",
        "activities-minutesSedentary",
        "activities-minutesLightlyActive",
        "activities-minutesFairlyActive",
        "activities-minutesVeryActive",
        "activities-steps",
        "activities-swimming-strokes",
        "activities-tracker-activityCalories",
        "activities-tracker-calories",
        "activities-tracker-distance",
        "activities-tracker-elevation",
        "activities-tracker-floors",
        "activities-tracker-minutesSedentary",
        "activities-tracker-minutesLightlyActive",
        "activities-tracker-minutesFairlyActive",
        "activities-tracker-minutesVeryActive",
        "activities-tracker-steps",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetActivityTimeSeriesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in activities_activity_calories (list)
        _items = []
        if self.activities_activity_calories:
            for _item_activities_activity_calories in self.activities_activity_calories:
                if _item_activities_activity_calories:
                    _items.append(_item_activities_activity_calories.to_dict())
            _dict["activities-activityCalories"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_calories (list)
        _items = []
        if self.activities_calories:
            for _item_activities_calories in self.activities_calories:
                if _item_activities_calories:
                    _items.append(_item_activities_calories.to_dict())
            _dict["activities-calories"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_calories_bmr (list)
        _items = []
        if self.activities_calories_bmr:
            for _item_activities_calories_bmr in self.activities_calories_bmr:
                if _item_activities_calories_bmr:
                    _items.append(_item_activities_calories_bmr.to_dict())
            _dict["activities-caloriesBMR"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_distance (list)
        _items = []
        if self.activities_distance:
            for _item_activities_distance in self.activities_distance:
                if _item_activities_distance:
                    _items.append(_item_activities_distance.to_dict())
            _dict["activities-distance"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_elevation (list)
        _items = []
        if self.activities_elevation:
            for _item_activities_elevation in self.activities_elevation:
                if _item_activities_elevation:
                    _items.append(_item_activities_elevation.to_dict())
            _dict["activities-elevation"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_floors (list)
        _items = []
        if self.activities_floors:
            for _item_activities_floors in self.activities_floors:
                if _item_activities_floors:
                    _items.append(_item_activities_floors.to_dict())
            _dict["activities-floors"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_minutes_sedentary (list)
        _items = []
        if self.activities_minutes_sedentary:
            for _item_activities_minutes_sedentary in self.activities_minutes_sedentary:
                if _item_activities_minutes_sedentary:
                    _items.append(_item_activities_minutes_sedentary.to_dict())
            _dict["activities-minutesSedentary"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_minutes_lightly_active (list)
        _items = []
        if self.activities_minutes_lightly_active:
            for (
                _item_activities_minutes_lightly_active
            ) in self.activities_minutes_lightly_active:
                if _item_activities_minutes_lightly_active:
                    _items.append(_item_activities_minutes_lightly_active.to_dict())
            _dict["activities-minutesLightlyActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_minutes_fairly_active (list)
        _items = []
        if self.activities_minutes_fairly_active:
            for (
                _item_activities_minutes_fairly_active
            ) in self.activities_minutes_fairly_active:
                if _item_activities_minutes_fairly_active:
                    _items.append(_item_activities_minutes_fairly_active.to_dict())
            _dict["activities-minutesFairlyActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_minutes_very_active (list)
        _items = []
        if self.activities_minutes_very_active:
            for (
                _item_activities_minutes_very_active
            ) in self.activities_minutes_very_active:
                if _item_activities_minutes_very_active:
                    _items.append(_item_activities_minutes_very_active.to_dict())
            _dict["activities-minutesVeryActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_steps (list)
        _items = []
        if self.activities_steps:
            for _item_activities_steps in self.activities_steps:
                if _item_activities_steps:
                    _items.append(_item_activities_steps.to_dict())
            _dict["activities-steps"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_swimming_strokes (list)
        _items = []
        if self.activities_swimming_strokes:
            for _item_activities_swimming_strokes in self.activities_swimming_strokes:
                if _item_activities_swimming_strokes:
                    _items.append(_item_activities_swimming_strokes.to_dict())
            _dict["activities-swimming-strokes"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_activity_calories (list)
        _items = []
        if self.activities_tracker_activity_calories:
            for (
                _item_activities_tracker_activity_calories
            ) in self.activities_tracker_activity_calories:
                if _item_activities_tracker_activity_calories:
                    _items.append(_item_activities_tracker_activity_calories.to_dict())
            _dict["activities-tracker-activityCalories"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_calories (list)
        _items = []
        if self.activities_tracker_calories:
            for _item_activities_tracker_calories in self.activities_tracker_calories:
                if _item_activities_tracker_calories:
                    _items.append(_item_activities_tracker_calories.to_dict())
            _dict["activities-tracker-calories"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_distance (list)
        _items = []
        if self.activities_tracker_distance:
            for _item_activities_tracker_distance in self.activities_tracker_distance:
                if _item_activities_tracker_distance:
                    _items.append(_item_activities_tracker_distance.to_dict())
            _dict["activities-tracker-distance"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_elevation (list)
        _items = []
        if self.activities_tracker_elevation:
            for _item_activities_tracker_elevation in self.activities_tracker_elevation:
                if _item_activities_tracker_elevation:
                    _items.append(_item_activities_tracker_elevation.to_dict())
            _dict["activities-tracker-elevation"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_floors (list)
        _items = []
        if self.activities_tracker_floors:
            for _item_activities_tracker_floors in self.activities_tracker_floors:
                if _item_activities_tracker_floors:
                    _items.append(_item_activities_tracker_floors.to_dict())
            _dict["activities-tracker-floors"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_minutes_sedentary (list)
        _items = []
        if self.activities_tracker_minutes_sedentary:
            for (
                _item_activities_tracker_minutes_sedentary
            ) in self.activities_tracker_minutes_sedentary:
                if _item_activities_tracker_minutes_sedentary:
                    _items.append(_item_activities_tracker_minutes_sedentary.to_dict())
            _dict["activities-tracker-minutesSedentary"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_minutes_lightly_active (list)
        _items = []
        if self.activities_tracker_minutes_lightly_active:
            for (
                _item_activities_tracker_minutes_lightly_active
            ) in self.activities_tracker_minutes_lightly_active:
                if _item_activities_tracker_minutes_lightly_active:
                    _items.append(
                        _item_activities_tracker_minutes_lightly_active.to_dict()
                    )
            _dict["activities-tracker-minutesLightlyActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_minutes_fairly_active (list)
        _items = []
        if self.activities_tracker_minutes_fairly_active:
            for (
                _item_activities_tracker_minutes_fairly_active
            ) in self.activities_tracker_minutes_fairly_active:
                if _item_activities_tracker_minutes_fairly_active:
                    _items.append(
                        _item_activities_tracker_minutes_fairly_active.to_dict()
                    )
            _dict["activities-tracker-minutesFairlyActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_minutes_very_active (list)
        _items = []
        if self.activities_tracker_minutes_very_active:
            for (
                _item_activities_tracker_minutes_very_active
            ) in self.activities_tracker_minutes_very_active:
                if _item_activities_tracker_minutes_very_active:
                    _items.append(
                        _item_activities_tracker_minutes_very_active.to_dict()
                    )
            _dict["activities-tracker-minutesVeryActive"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in activities_tracker_steps (list)
        _items = []
        if self.activities_tracker_steps:
            for _item_activities_tracker_steps in self.activities_tracker_steps:
                if _item_activities_tracker_steps:
                    _items.append(_item_activities_tracker_steps.to_dict())
            _dict["activities-tracker-steps"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetActivityTimeSeriesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "activities-activityCalories": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-activityCalories"]
                ]
                if obj.get("activities-activityCalories") is not None
                else None,
                "activities-calories": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-calories"]
                ]
                if obj.get("activities-calories") is not None
                else None,
                "activities-caloriesBMR": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-caloriesBMR"]
                ]
                if obj.get("activities-caloriesBMR") is not None
                else None,
                "activities-distance": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-distance"]
                ]
                if obj.get("activities-distance") is not None
                else None,
                "activities-elevation": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-elevation"]
                ]
                if obj.get("activities-elevation") is not None
                else None,
                "activities-floors": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-floors"]
                ]
                if obj.get("activities-floors") is not None
                else None,
                "activities-minutesSedentary": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-minutesSedentary"]
                ]
                if obj.get("activities-minutesSedentary") is not None
                else None,
                "activities-minutesLightlyActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-minutesLightlyActive"]
                ]
                if obj.get("activities-minutesLightlyActive") is not None
                else None,
                "activities-minutesFairlyActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-minutesFairlyActive"]
                ]
                if obj.get("activities-minutesFairlyActive") is not None
                else None,
                "activities-minutesVeryActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-minutesVeryActive"]
                ]
                if obj.get("activities-minutesVeryActive") is not None
                else None,
                "activities-steps": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-steps"]
                ]
                if obj.get("activities-steps") is not None
                else None,
                "activities-swimming-strokes": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-swimming-strokes"]
                ]
                if obj.get("activities-swimming-strokes") is not None
                else None,
                "activities-tracker-activityCalories": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-activityCalories"]
                ]
                if obj.get("activities-tracker-activityCalories") is not None
                else None,
                "activities-tracker-calories": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-calories"]
                ]
                if obj.get("activities-tracker-calories") is not None
                else None,
                "activities-tracker-distance": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-distance"]
                ]
                if obj.get("activities-tracker-distance") is not None
                else None,
                "activities-tracker-elevation": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-elevation"]
                ]
                if obj.get("activities-tracker-elevation") is not None
                else None,
                "activities-tracker-floors": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-floors"]
                ]
                if obj.get("activities-tracker-floors") is not None
                else None,
                "activities-tracker-minutesSedentary": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-minutesSedentary"]
                ]
                if obj.get("activities-tracker-minutesSedentary") is not None
                else None,
                "activities-tracker-minutesLightlyActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-minutesLightlyActive"]
                ]
                if obj.get("activities-tracker-minutesLightlyActive") is not None
                else None,
                "activities-tracker-minutesFairlyActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-minutesFairlyActive"]
                ]
                if obj.get("activities-tracker-minutesFairlyActive") is not None
                else None,
                "activities-tracker-minutesVeryActive": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-minutesVeryActive"]
                ]
                if obj.get("activities-tracker-minutesVeryActive") is not None
                else None,
                "activities-tracker-steps": [
                    ActivityTimeSeriesDatapoint.from_dict(_item)
                    for _item in obj["activities-tracker-steps"]
                ]
                if obj.get("activities-tracker-steps") is not None
                else None,
            }
        )
        return _obj
