"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict
from typing_extensions import Self

from fitbit_web_api.models.lifetime_stats_best_total_distance import (
    LifetimeStatsBestTotalDistance,
)
from fitbit_web_api.models.lifetime_stats_best_total_floors import (
    LifetimeStatsBestTotalFloors,
)
from fitbit_web_api.models.lifetime_stats_best_total_steps import (
    LifetimeStatsBestTotalSteps,
)


class LifetimeStatsBestTracker(BaseModel):
    """
    The user's best achievements including tracker data only.
    """

    distance: Optional[LifetimeStatsBestTotalDistance] = None
    floors: Optional[LifetimeStatsBestTotalFloors] = None
    steps: Optional[LifetimeStatsBestTotalSteps] = None
    __properties: ClassVar[List[str]] = ["distance", "floors", "steps"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LifetimeStatsBestTracker from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of distance
        if self.distance:
            _dict["distance"] = self.distance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floors
        if self.floors:
            _dict["floors"] = self.floors.to_dict()
        # override the default output from pydantic by calling `to_dict()` of steps
        if self.steps:
            _dict["steps"] = self.steps.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LifetimeStatsBestTracker from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "distance": LifetimeStatsBestTotalDistance.from_dict(obj["distance"])
                if obj.get("distance") is not None
                else None,
                "floors": LifetimeStatsBestTotalFloors.from_dict(obj["floors"])
                if obj.get("floors") is not None
                else None,
                "steps": LifetimeStatsBestTotalSteps.from_dict(obj["steps"])
                if obj.get("steps") is not None
                else None,
            }
        )
        return _obj
