"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self

from fitbit_web_api.models.logged_food_unit import LoggedFoodUnit


class LoggedFood(BaseModel):
    """
    LoggedFood
    """

    access_level: Optional[StrictStr] = Field(
        default=None, description="The access level of the food.", alias="accessLevel"
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="The amount of food consumed."
    )
    brand: Optional[StrictStr] = Field(
        default=None, description="The brand of the food."
    )
    calories: Optional[StrictInt] = Field(
        default=None, description="The calories in the food."
    )
    food_id: Optional[StrictInt] = Field(
        default=None, description="The ID of the food.", alias="foodId"
    )
    locale: Optional[StrictStr] = Field(
        default=None, description="The locale of the food."
    )
    meal_type_id: Optional[StrictInt] = Field(
        default=None, description="The meal type ID.", alias="mealTypeId"
    )
    name: Optional[StrictStr] = Field(default=None, description="The name of the food.")
    unit: Optional[LoggedFoodUnit] = None
    units: Optional[List[StrictInt]] = Field(
        default=None, description="List of unit IDs."
    )
    __properties: ClassVar[List[str]] = [
        "accessLevel",
        "amount",
        "brand",
        "calories",
        "foodId",
        "locale",
        "mealTypeId",
        "name",
        "unit",
        "units",
    ]

    @field_validator("access_level")
    def access_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["PUBLIC", "PRIVATE"]):
            raise ValueError("must be one of enum values ('PUBLIC', 'PRIVATE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoggedFood from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """
        Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of unit
        if self.unit:
            _dict["unit"] = self.unit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoggedFood from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "accessLevel": obj.get("accessLevel"),
                "amount": obj.get("amount"),
                "brand": obj.get("brand"),
                "calories": obj.get("calories"),
                "foodId": obj.get("foodId"),
                "locale": obj.get("locale"),
                "mealTypeId": obj.get("mealTypeId"),
                "name": obj.get("name"),
                "unit": LoggedFoodUnit.from_dict(obj["unit"])
                if obj.get("unit") is not None
                else None,
                "units": obj.get("units"),
            }
        )
        return _obj
